### ISSUE TITLE
What are the prerequisites ?

### ISSUE THREAD

**Issue by bertman80** [Diverto/nse-log4shell#10]
Looks like i'm missing an item, but what ?

**Input**
`nmap -sV -T4 -v -d --script=$PWD/ 10.16.12.15`

**Output:**
NSE: Using Lua 5.3.
NSE: Arguments from CLI:
NSE: module 'libssh2' not found:
        NSE failed to find nselib/libssh2.lua in search paths.
        no field package.preload['libssh2']
        no file '/usr/local/share/lua/5.3/libssh2.lua'
        no file '/usr/local/share/lua/5.3/libssh2/init.lua'
        no file '/usr/local/lib/lua/5.3/libssh2.lua'
        no file '/usr/local/lib/lua/5.3/libssh2/init.lua'
        no file './libssh2.lua'
        no file './libssh2/init.lua'
        no file '/usr/local/lib/lua/5.3/libssh2.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './libssh2.so'
stack traceback:
        /usr/bin/../share/nmap/nse_main.lua:293: in function 'stdnse.silent_require'
        /usr/bin/../share/nmap/nselib/libssh2-utility.lua:14: in main chunk
        [C]: in function 'require'
        /root/nse-log4shell//ssh-log4shell.nse:4: in function </root/nse-log4shell//ssh-log4shell.nse:1>
NSE: Failed to load '/root/nse-log4shell//ssh-log4shell.nse'.
NSE: Loaded 47 scripts for scanning.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 2) scan.
........

**Whereis**
`whereis lua`
lua: /usr/bin/lua /usr/lib64/lua /usr/share/lua /usr/share/man/man1/lua.1.gz

Package libssh2-1.9.0-5.el8.x86_64 is already installed.

**OS**
`cat /etc/os-release`
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

**Comment by bertman80** [comment]
After a reboot it works

**Comment by bertman80** [comment]
sry problem still exists for: **NSE: Failed to load '/root/nse-log4shell//ssh-log4shell.nse'**

**Comment by bertman80** [comment]
update was the sollution, sry for the spam :P

**Comment by kost** [comment]
No problem. Glad you fixed it. Probably because you had old version of Nmap or your version of Nmap was compiled without libssh2.

Good luck with your scans!
